### ISSUE TITLE
Zadání - nutnost jednoho z atributů v sekci stats

### ISSUE THREAD

**Issue by tomasis98** [cvut/committee#1]
Dotaz se týká [pravidel pro stats](https://github.com/cvut/committee/tree/basic#pravidlo-stats)

Není podmínka nutnosti alespoň jednoho z atributů splněna z podstaty zadání? Pokud uživatel do configu nezadá `min` ani  `max`, tak do `min` se přiřadí hodnota 0. Tím pádem se splní podmínka přítomnosti jednoho z atributů.

**Comment by hroncok** [comment]
Rozumněl bych tomu tak, že je povinný alespoň jeden z atributů min a max ručně zadaný.

**Comment by tomasis98** [comment]
Chápu, děkuji.
