### ISSUE TITLE
Testy a colorama

### ISSUE THREAD

**Issue by Lznah** [cvut/committee#3]
Mám problém s testy u "nastylování" výstupu coloramou. Při její použítí testy nepočítají s přidanými neviditelnými znaky a zbytečně selhávají.

Workaround:
Style.BRIGHT = ""
Style.RESET_ALL = ""
Fore.RED = ""
Fore.GREEN = ""
Fore.YELLOW = ""
Fore.RESET = ""
Fore.MAGENTA = ""

Omlouvám se, pokud jste toto zmiňovali třeba během cviku.

**Comment by hroncok** [comment]
click.echo (a secho) by měl barvy stripnout, pokud sype výstup do pajpy. Na Linuxu to funguje bez problémů, na Windows asi záleží na konstelaci hvězd.

Pro jistotu ale zdůrazním, že obyčejný print to nedělá.

**Comment by Lznah** [comment]
Super, přesně jak říkáš.
