### ISSUE TITLE
Test: message_regex

### ISSUE THREAD

**Issue by Lznah** [cvut/committee#4]
Prohozené řádky v testu:
Je takto:
`   
    assert lines[20] == '  -> file-or-files: FAIL'
    assert lines[21] == '     - Yah, certainly there are some files...'
    assert lines[22] == '  -> junk-in-the-end: PASS'
    assert lines[23] == '  -> too-short-message: PASS'
    assert lines[24] == '  ~> Updating commit status: DRY-RUN'
    assert lines[25] == '  => FAILURE - The commit violates rules: file-or-files.'`
Myslím si, že by mělo být takto:
`
    assert lines[20] == '  -> junk-in-the-end: PASS'
    assert lines[21] == '  -> too-short-message: PASS'
    assert lines[22] == '  -> file-or-files: FAIL'
    assert lines[23] == '     - Yah, certainly there are some files...'
    assert lines[24] == '  ~> Updating commit status: DRY-RUN'
    assert lines[25] == '  => FAILURE - The commit violates rules: file-or-files.'
`
Protože v message_regex.cfg je pravidlo file-or-files: níže
Stejně by to tedy mělo být i pro ostatní commity ve stejném testu. Zatím jsem nekontroloval ostatní testy.

**Comment by MarekSuchanek** [comment]
Ze zadání:

> Dále aplikace s pravidly pracuje v abecedním pořadí.

Pořadí tedy není určeno pořadím pravidel v konfiguračním souboru.

**Comment by Lznah** [comment]
Jasné, díky :)
