### ISSUE TITLE
Missing required positional argument in run method

### ISSUE THREAD

**Issue by cowjen01** [cvut/committee#5]
There is a bug in the test's helper method `run` which expects 1 required positional argument `entrypoint`. There should be a default value set to `False` because the method is also called with `entrypoint` argument omitted:

```python
hlp_m = run('--help')
hlp_e = run('--help', entrypoint=True)
```

It leads to an error in module tests:

```
def test_incorrect_config(config_name):
        """And if they don't forget, it still may be incorrect"""
>       cp = run(f'--config "{config(config_name)}" '
                 f'something/dummy')
E       TypeError: run() missing 1 required positional argument: 'entrypoint'
```

Possible solution is:

```python
def run(line, entrypoint=False, **kwargs):
   pass
```

**Comment by hroncok** [comment]
Indeed,could you please send a Pull Request?
